### ISSUE TITLE
M2 Faucet Buggy

### ISSUE THREAD

**Issue by MarcelCloud** [movementlabsxyz/faucet#10]
Hey Team,

I have tried to use the M2 faucet support  [https://faucet.movementlabs.xyz/?network=devnet](url) and Razor's in-app faucet (Screenshot attached) — but there seems to be a backend problem or downtime on the M2 testnet server.
@l-monninger 
![IMG_5995](https://github.com/movementlabsxyz/faucet/assets/141267512/d1aeb027-46c8-4a7b-b553-ebeedd58652c)
![IMG_5996](https://github.com/movementlabsxyz/faucet/assets/141267512/f312857d-32ab-492c-94ed-85e8175e35e0)
![IMG_5997 2](https://github.com/movementlabsxyz/faucet/assets/141267512/38156649-3085-4807-9f64-76451fbaeff3)

**Comment by l-monninger** [comment]
@0xPrimata @andygolay for completeness, please comment here once we are confident with the applied fix.
